services:
  - type: web
    name: task-manager
    env: python
    buildCommand: pip install -r app/requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app.app
    envVars:
      - key: ENV
        value: prod
      - key: PORT
        value: 10000
